### ISSUE TITLE
Can't `want: false` in taptest

### ISSUE THREAD

**Issue by m-dango** [yaml/yamlscript#180]
Unsure if I'm doing something wrong but I seem to be unable to use `false` in a taptest check:

```yaml
#!/usr/bin/env ys-0

require ys::taptest: :all

use: 'leap'

plan: 1

test::
- name: year not divisible by 4 in common year
  eval: leap/is-leap-year(2015)
  want: false
```

```
1..1
Error: taptest: Test 1 requires one of: 'want', 'like', 'has'
```
